DZ/lab5/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.defaults import page_not_found


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('my_app.urls')),
    #url(r'class_based_view/', ExampleClassBased.as_view())
]

DZ/my_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from .views import *

urlpatterns = [
    url(r'^basextend/', basextend, name='basextend'),
    url(r'^basepage/', basepage, name='basepage'),
    url(r'^testpage/', testpage, name='testpagebase'),
    url(r'^computers/page/(?P<id>\d+)', PageView.as_view(), name='page'),
    url(r'^inclpage/', IncludePage.as_view(), name="includepage"),
    url(r'^$', AuthorizeDjango, name='AuthorizeDjango'),
    url(r'computers/', login_required(ComputersClass.as_view()), name="computers"),
    # url(r'registration/', RegisterClass, name="registration"),
    # url(r'authorization/', authorization, name="authorization"),
    url(r'register/', RegisterDjango, name="RegisterDjango"),
    url(r'authorize/', AuthorizeDjango, name="AuthorizeDjango"),
    url(r'logout/', LogoutClass, name="LogoutClass"),
    url(r'scroll/', InfiniteScroll.as_view(), name="InfiniteScroll"),

]

DZ/my_app/models.py
from django.db import models


class ComputerModel(models.Model):
    class Meta:
        db_table = 'my_app_computer'
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=255)
    picpath = models.CharField(max_length=255, blank=True, default="")

    def __str__(self):
        return " id: {}, name:{}, description:{}".format(self.id, self.name, self.description, self.picpath)


class CustomerModel(models.Model):
    class Meta:
        db_table = 'my_app_customer'

    login = models.CharField(max_length=64, default='')
    secondname = models.CharField(max_length=64, default='')
    firstname = models.CharField(max_length=64, default='')
    email = models.CharField(max_length=64)
    password = models.CharField(max_length=300)
    computers = models.ManyToManyField(ComputerModel, through='OrderModel')

    def __str__(self):
        return "id : {}, login:{}, secondname:{}, firstname:{}, email:{}".format(self.id, self.login,
                                                                                              self.secondname,
                                                                                              self.firstname,
                                                                                              self.email,
                                                                                              )


class OrderModel(models.Model):
    class Meta:
        db_table = 'my_app_order'

    customer = models.ForeignKey(CustomerModel, on_delete=models.CASCADE)
    computer = models.ForeignKey(ComputerModel, on_delete=models.CASCADE)
    date_received = models.DateField()
    date_completed = models.DateField()
    status = models.BooleanField(default=False)

    def __str__(self):
        return " customer:{}, computer:{}, date_received:{}, date_completed:{}, status:{}".format(
            self.customer,
            self.computer,
            self.date_received,
            self.date_completed,
            self.status)

DZ/my_app/forms.py
from django import forms
from .models import *


class RegisterForm(forms.ModelForm):
    class Meta:
        model = CustomerModel
        exclude = ["computers", "login", "password", "secondname", "firstname"]

    firstname = forms.CharField(label="Имя", )
    secondname = forms.CharField(label="Фамилия", )
    email = forms.EmailField(label="e-mail")
    login = forms.CharField(min_length=5, label="Логин", )
    password = forms.CharField(min_length=8, widget=forms.PasswordInput, label="Введите пароль", )
    password2 = forms.CharField(min_length=8, widget=forms.PasswordInput, label="Повторите пароль", )

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['firstname'].widget.attrs.update({'class' : 'form-control', 'placeholder':'Введите Имя'})
        self.fields['secondname'].widget.attrs.update({'class': 'form-control', 'placeholder':'Введите Фамилию'})
        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите Ваш email'})
        self.fields['login'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите Логин'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Повторите пароль'})
        self.fields['password'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Пароль'})


class AuthorizeForm(forms.ModelForm):
    class Meta:
        model = CustomerModel
        exclude = ["computers", "firstname", "secondname", "email"]

    login = forms.CharField(min_length=5, label="Логин", )
    password = forms.CharField(min_length=8, widget=forms.PasswordInput, label="Введите пароль", )
    def __init__(self, *args, **kwargs):
        super(AuthorizeForm, self).__init__(*args, **kwargs)
        self.fields['login'].widget.attrs.update({'class' : 'form-control', 'placeholder':'Логин'})
        self.fields['password'].widget.attrs.update({'class': 'form-control', 'placeholder':'Пароль'})

class ComputerForm(forms.ModelForm):
    class Meta:
        model = ComputerModel
        exclude = ['picpath']

    name = forms.CharField(label="Название")
    description = forms.CharField(label="Описание")
    file = forms.FileField(label="Выберите файл", allow_empty_file=True)
    def __init__(self, *args, **kwargs):
        super(ComputerForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class' : 'form-control', 'placeholder':'Название'})
        self.fields['description'].widget.attrs.update({'class': 'form-control', 'placeholder':'Описание'})

class DateInput(forms.DateInput):
    input_type = "date"

class OrderForm(forms.ModelForm):
    class Meta:
        model = OrderModel

        fields = ['date_completed']
        widgets = {
            'date_completed': DateInput()
        }
        labels = {
            'date_completed': "Введите дату исполнения заказа"
        }

DZ/my_app/views.py
from django.contrib.auth import authenticate, login as login_user, logout
from django.shortcuts import render, redirect
import os
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
import datetime
from django.views import View
from my_app.models import ComputerModel, CustomerModel, OrderModel
from lab5.settings import BASE_DIR, LOGIN_URL, STATICFILES_DIRS
from .forms import RegisterForm, AuthorizeForm, ComputerForm, OrderForm
from hashlib import md5, sha256
from django.contrib.auth.hashers import *
from django.contrib.auth.models import User
import json, math
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



def basepage(request):
    return render(request, "my_app/base.html")


def basextend(request):
    colors = {
        'colors': {"black": "#000000", "white": "#FFFFFF", "red1": "#FF0000", "green": "#00FF00", "blue": "#0000FF"}}
    return render(request, "my_app/basextend.html", colors)


def testpage(request):
    pages = [
        {'title': "Первая страница", "id": 1},
        {'title': "Вторая страница", "id": 2},
        {'title': "Третья страница", "id": 3}
    ]
    server_times = {'date': datetime.datetime.now()}
    dicts = {"pages": pages, "server_times": server_times}
    return render(request, "my_app/index.html", dicts)


def orderview(request):
    return render('my_app/ordermodal.html')


class PageView(View):
    def post(self, request, id):
        # Adding New Computer ajax
        names_dict = {}
        errors = []
        newobjectform = OrderForm(request.POST, request.FILES)
        if request.method == "POST" and newobjectform.is_valid() and request.is_ajax():
            allowed_files = ['png', 'svg', 'jpeg', 'jpg', 'gif']
            data = newobjectform.cleaned_data
            names_list = ["date_completed"]
            names_dict = {x: request.POST.get(x, "") for x in names_list}

            date_completed = data["date_completed"]
            if not date_completed:
                errors.append('Введите необходимую дату исполнения заказа')

            msg = ""
            if not errors:
                customer_data = CustomerModel.objects.get(login__exact=request.user.username)
                computer_data = ComputerModel.objects.get(id=id)

                OrderModel.objects.create(customer=customer_data, computer=computer_data, date_completed=date_completed,
                                          date_received=datetime.date.today(), status=False)

                msg = "Заказ успешно добавлен!" + " " + "Логин: " + str(
                    customer_data.login) + " " + "Компьютер: " + str(computer_data.name)
            json_response = json.dumps({'errors': errors, 'msg': msg})
            return HttpResponse(json_response, content_type="application/json")
        json_response = json.dumps({'errors': errors, 'msg': "Something went wrong, try again"})
        return HttpResponse(json_response, content_type="application/json")

    def get(self, request, id):
        plist = os.listdir(os.path.join(BASE_DIR, "static"))
        pics = {el.rsplit('.', 1)[0]: el for el in plist}
        computer = ComputerModel.objects.get(id=int(id))
        customers = []
        customers = CustomerModel.objects.values('login').filter(ordermodel__computer_id=int(id)).distinct()
        newobjectform = OrderForm(request.POST or None)
        return render(request, 'my_app/page.html',
                      {'computer': computer, 'pics': pics, 'customers': customers, 'newobjectform': newobjectform})


class IncludePage(View):
    def get(self, request):
        return render(request, 'my_app/inclpage.html')

"""
def authorization(request):
    names_dict = {}
    errors = []

    if request.method == "POST":
        names_list = ["username", "password"]
        names_dict = {x: request.POST.get(x, "") for x in names_list}
        username = request.POST.get("username")
        if not username:
            errors.append('Введите логин')
        password = request.POST.get('password')
        if not password:
            errors.append("Введите пароль")
        if not errors:
            return HttpResponseRedirect("/computers/")
    print(list(errors))
    return render(request, 'my_app/authorization.html', {"errors": errors, 'names_dict': names_dict})
"""


# Форма средствами Django
def RegisterDjango(request):
    names_dict = {}
    errors = []
    form = RegisterForm(request.POST or None)
    # TODO заменить на методы класса
    if request.method == "POST" and form.is_valid():
        data = form.cleaned_data
        names_list = ["firstname", "password", "email", "secondname", "login", "password2"]
        names_dict = {x: request.POST.get(x, "") for x in names_list}

        login = data["login"]

        if not login:
            errors.append('Введите логин')
        elif len(login) < 5:
            errors.append("Логин должен содержать не менее 5 симоволов")

        password = data['password']
        if not password:
            errors.append("Введите пароль")
        elif len(password) < 8:
            errors.append("Длина пароля должна быть не менее 8 символов")
        elif password != data["password2"]:
            errors.append("Пароли не совпадают")

        email = data['email']
        if not email:
            errors.append("Введите e-mail")

        firstname = data['firstname']
        if not firstname:
            errors.append("Введите Имя")

        secondname = data['secondname']
        if not secondname:
            errors.append("Введите Фамилию")

        if not errors:
            # updating data for registration
            new_form = form.save(commit=False)
            new_form.login = data.get('login')
            new_form.firstname = data.get('firstname')
            new_form.secondname = data.get('secondname')
            new_form.password = data.get('password')
            new_form.email = data.get('email')

            user = User.objects.create_user(username= new_form.login, password=new_form.password, email = new_form.email)
            print(user.password)
            new_form.password = user.password
            print(new_form.password)
            new_form.save()
            form.save_m2m()
            return HttpResponseRedirect("/authorize/")
    return render(request, 'my_app/register.html', {"errors": errors, 'names_dict': names_dict, "form": form})


def AuthorizeDjango(request):
    names_dict = {}
    errors = []
    form = AuthorizeForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        data = form.cleaned_data
        names_list = ["login", "password"]
        names_dict = {x: request.POST.get(x, "") for x in names_list}

        login = data["login"]
        if not login:
            errors.append('Введите логин')
        password = data['password']

        if not password:
            errors.append("Введите пароль")

        if not errors:
            try:
                userdata = CustomerModel.objects.get(login=data["login"])
                if not check_password(data.get('password'), userdata.password):
                    errors.append("Неправильное имя пользователя или пароль")

            except CustomerModel.DoesNotExist:
                errors.append("Неправильное имя пользователя")

            if not errors:
                user = authenticate(username=login, password=data.get('password'))
                if user is not None:
                    if request.user.is_authenticated():
                        pass
                    login_user(request, user)
                    return HttpResponseRedirect("/computers/")
    print(list(errors))
    return render(request, 'my_app/authorize.html', {"errors": errors, 'names_dict': names_dict, "form": form})


class ComputersClass(View):
    def post(self, request):
        if request.content_type == "multipart/form-data":
            # Adding New Computer ajax
            filename = ""
            names_dict = {}
            errors = []
            newobjectform = ComputerForm(request.POST, request.FILES)
            if request.method == "POST" and newobjectform.is_valid():

                image = False
                data = newobjectform.cleaned_data
                names_list = ["name", "description"]
                names_dict = {x: request.POST.get(x, "") for x in names_list}

                name = data["name"]
                if not name:
                    errors.append('Введите название')
                if (len(name) < 5):
                    errors.append("Название должно содержать не менее 5 символов")
                description = data['description']
                if not description:
                    errors.append("Введите Описание")
                msg = ""
                if not errors:
                    print(STATICFILES_DIRS[0] + "\\" + data.get('name').lower() + '.txt')

                    new_form = newobjectform.save(commit=False)
                    filepath = str(STATICFILES_DIRS[0] + "\\" + data.get('name').lower() + '.txt')
                    new_form.name = data.get('name')
                    new_form.description = data.get('description')
                    new_form.save()
                    newobjectform.save_m2m()
                    print(data.get('file'))
                    if request.FILES['file']:
                        with open(filepath, 'wb+') as destination:
                            for chunk in request.FILES['file'].chunks():
                                destination.write(chunk)
                    msg = "Объект успешно добавлен!"
                    filename = data.get('name').lower()
                json_response = json.dumps({'errors': errors, 'msg': msg, 'filename': filename})
                return HttpResponse(json_response, content_type="application/json")

            json_response = json.dumps({'errors': errors, 'msg': "Something went wrong, try again"})
            return HttpResponse(json_response, content_type="application/json")

DZ/templates/my_app/AddingModal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>modalform</title>
</head>
<body>

</body>
</html>

DZ/templates/my_app/authorization.html
{% extends 'my_app/base.html' %}
{% load static %}
{% load template_filters %}
{% block title %}Autorization{% endblock %}

{% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link rel="apple-touch-icon" href="{% static 'iphone_icon.png' %}">
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
    <link rel="icon" type="image/png" href="{% static 'favicon.png' %}">
    <!--<link rel = "stylesheet" href ="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">-->
    <link rel="stylesheet" href="{% static '/style.css' %}">
    <link rel="stylesheet" href="{% static '/bootstrap.min.css' %}">
{% endblock %}

{% block content %}

    {% if errors %}
        <div class="alert alert-warning" role="alert">
            {% for x in errors %}
                {{ x }}
            {% endfor %}
        </div>
    {% else %}
        <div class=""
             style="padding: 15px; margin-bottom: 40px;border: 1px solid transparent;box-sizing: border-box;"></div>
    {% endif %}
    <div class="container" style="">

        <div class="col-lg-6 col-lg-offset-3" style="border: 2px solid slategray; ">
            <form method="POST">
                {% csrf_token %}
                <h3 class="title text-center text-info">Авторизация</h3>
                <div class="col-lg-12 col-lg-offset-0">
                    <div class="form-row" style="margin-bottom: 5%">
                        <input type="text" name="username" autocomplete="off" autofocus class="form-control form-group"
                               placeholder="Логин" value="{{ names_dict|get_item:"username" }}">
                        <input type="text" name="password" autocomplete="off" class="form-control form-group"
                               placeholder="Пароль" value="{{ names_dict|get_item:"password" }}">
                    </div>
                    <div class="submit-row" style="margin-bottom: 7%">
                        <button class="btn btn-default" type="submit">Войти</button>
                        <a class="btn btn-default" type="button" href="https://google.com/">Отмена</a>
                        <div class="regbuttn">
                            <a href="{% url 'registration' %}">регистрация</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <script src="{% static "/jscript.js" %}"></script>

{% endblock %}
{% block footer %}

{% endblock %}

DZ/templates/my_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}
        <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link rel="apple-touch-icon" href="{% static 'iphone_icon.png' %}" >
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <link rel = "icon" type = "image/png" href="{% static 'favicon.png' %}">
    <!--<link rel = "stylesheet" href ="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">-->
    <link rel = "stylesheet" href ="{% static '/style.css' %}">
    <!--<link rel = "stylesheet" href ="{% static '/bootstrap.min.css' %}">-->
    {% endblock %}
</head>
<body>
{% block content %}{% endblock %}
{% block footer %}{% endblock %}
</body>
</html>

DZ/templates/my_app/basextend.html
{% extends 'my_app/base.html' %}
{% load static %}
{% block title %}Extend{% endblock %}
{% block head %}<style> .txt{ color: {{ colors.red1 }}; } </style>{% endblock %}
{% block content %}
    <h2>extended page from <i>my_app/base.html</i> </h2>
    <div class="txt">Цветная строка</div>
    <b>Список цветов:</b>
    <ul>
        {% for k,v in colors.items %}
            <li>{{ k }} = {{ v }}</li>
        {% endfor %}
    </ul>
{% endblock %}

DZ/templates/my_app/computers.html
{% extends 'my_app/base.html' %}
{% block title %} My_app {% endblock %}
{% block head %}
    {% load static %}
    {% load template_filters %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link rel="apple-touch-icon" href="{% static 'iphone_icon.png' %}">
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
    <link rel="icon" type="image/png" href="{% static 'favicon.png' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
    <!--<link rel = "stylesheet" href ="{% static '/bootstrap.min.css' %}">-->
    <link rel="stylesheet" href="{% static '/style.css' %}">
{% endblock %}
{% block content %}

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Название сайта</a>
            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href={% url 'testpagebase' %}>Заказы</a>
                    </li>
                    <li class="active">
                        <a href=#>Товары<span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Найти">
                    </div>
                    <button type="submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </form>
                <ul class="nav navbar-nav navbar-right ">
                    <li><a class="btn" href= {% url 'LogoutClass' %}>{{ user }}&nbsp (Выйти)
                    </a></li>
                </ul>
            </div>

        </div>
    </nav>

    <div class="container">
        <ol class="breadcrumb crumbs">
            <li><a href="{% url 'testpagebase' %}"><span class="glyphicon glyphicon-home"></span></a></li>
            <li><a href="{% url 'testpagebase' %}">Главная</a></li>
            <li class="active">Товары</li>
        </ol>
    </div>

    <!-- Должен быть список с элементами и ссылками на подробное описание-->
    <div class="container">
        <div class="col-lg-3 col-lg-offset-1">
            <ul id='pag_container' class="list-unstyled">

            </ul>
            <div id="loading_ind" class="text-info " style ="margin-bottom: 20px; font-size: 16px">...</div>
        </div>
    </div>
    <div class="user-container">

    </div>

    <button class="circle-button" data-toggle="modal" data-target="#ModalAddItem">+</button>
    <div id="ModalAddItem" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" type="button" data-dismiss="modal">×</button>
                    <h4 class="modal-title">Добавление объекта</h4>
                </div>
                <div id="AddingModal">
                    <div id="AddingModalForm_Errors">

                    </div>
                    <form action='{% url "computers" %}' enctype="multipart/form-data" method="POST"
                          id="AddingModalForm" novalidate>
                        {% csrf_token %}
                        <div class="modal-body">
                            {{ newobjectform.as_p }}
                            <img src="{% static '404.jpg' %}" id="imageframe"
                                 style=" width: 90px; height: 90px; display: inline-block">
                        </div>
                        <div class="modal-footer">
                            <button id = "AddingModalFormButton" class="btn btn-default"   type="submit">Добавить</button>
                            <button class="btn btn-default" type="button" data-dismiss="modal">Закрыть</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>

    <script src="{% static "/jscript.js" %}"></script>
    <script>

        //Форма создания объекта
        var frm = $('#AddingModalForm');
        var data;
        frm.submit(function () {
            data = new FormData($(this));
            data.append('name', $('#id_name').val());
            data.append('description', $('#id_description').val());
            data.append('file', $('#id_file')[0].files[0]);
            csrf_token = "{{ csrf_token }}";

            $.ajax({
                type: frm.attr('method'),
                url: frm.attr('action'),
                data: data,
                /*data: frm.serialize(),*/
                dataType: 'json',
                processData: false,
                cache: false,
                contentType: false,
                headers: {'X-CSRFToken': csrf_token},
                success: function (response) {
                    $("#AddingModalForm_Errors").html(response.errors + response.msg);
                    $('#imageframe').attr("src", "/static/" + response.filename + '.txt');
                },
                error: function (response) {
                    $("#AddingModalForm_Errors").html("Something went wrong!");
                    $("#AddingModalForm_Errors").html(response.errors);
                    $('#imageframe').attr('src', "{% static '404.jpg' %}");
                }
            });
            return false;
        });
        //Беск. прокрутка
        function LoadContent(page_number) {
            csrf_token = "{{ csrf_token }}";
            $.ajax({
                url: "{% url 'InfiniteScroll' %}",
                type: "GET",
                data: 'action=infinite_scroll&page_number=' + page_number,
                headers: {'X-CSRFToken': csrf_token},
                success: function (response) {
                    $("#pag_container").append(response);
                },
                error: function (response) {
                    $("#pag_container").append("an error occured, try again");
                }


            });
        }
        //Текущая страница
        var page_number = 1;
        //Обнаружение конца страницы и загрузка новых элементов
        $(window).scroll(
            function () {
                if ($(window).scrollTop() == $(document).height() - $(window).height()) {

                    document.getElementById("loading_ind").textContent='...' ;
                    console.log("End of page reached!");

                    //Подгрузка новых элементов
                    if (page_number <= {{ page_quantity }})
                    {
                        LoadContent(page_number);
                        page_number++;

                    }
                    else{
                        document.getElementById("loading_ind").textContent='конец списка';
                    }

                }
            });

        $(document).ready(
            function(){
                document.getElementById("loading_ind").textContent='...' ;
                LoadContent(page_number);
                page_number++;
            });

        //Валидация формы добавления объекта
         $(document).ready(
             function(){
                 $('#AddingModalForm').validate({
                     rules:{
                         name:{
                             required:true,
                             minlength:"5",
                             maxlength:"30"
                         },
                         description:{
                             required:true,
                             minlength:"5",
                             maxlength:"255"},
                         file:{
                             required:true
                         }
                     },
                     messages:{
                         name:{
                             required:"Заполните это поле",
                             minlength:"Длина названия должна быть не менее 5 символов",
                             maxlength:"Длина названия должна быть не более 30 символов"
                         },
                         description:{
                             required:"Заполните это поле",
                             minlength:"Длина описания должна быть не менее 5 символов",
                             maxlength:"Длина описания должна быть не более 255 символов"
                         },
                         file:{
                             required:"Заполните это поле"
                         }
                     },
                     success: function(){$("#AddingModalFormButton").attr('disabled', false);},

                 })
             });

    </script>
{% endblock %}

{% block footer %}

{% endblock %}

DZ/templates/my_app/inclpage.html
{% extends 'my_app/base.html' %}
{% block title %}IncludePage {% endblock %}
{% block head %}{% endblock %}
{% block content %}
    <li><a href = "{% url 'page' element.id %}">{{ element.title }} included page</a></li>
{% endblock %}

DZ/templates/my_app/inf_page_element.html
<!DOCTYPE html>
{% load static %}
{% load template_filters %}

{% for pc in numbers %}
    <li>
        <div class="container">
            <div class="col-lg-8 col-lg-offset-0">
                {% if pc.name.lower in pics.keys %}
                    <img src="{% static pics|get_item:pc.name.lower %}" class="pcpic">
                {% else %}
                    <img src="{% static  '404.jpg' %}" class="pic404">
                {% endif %}
                <div class="pcdesc">
                    <a href="{% url 'page' pc.id %}">{{ pc.name }}</a>
                </div>

            </div>
        </div>
    </li>
{% empty %}
    <li>Элементов нет</li>
{% endfor %}