lab_6/Entertainment/Entertainment/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^gilp/', include('gilp.urls')),
]

lab_6/Entertainment/gilp/urls.py
from django.conf.urls import url

from . import views

app_name = 'gilp'

urlpatterns = [
    #url(r'^$', views.index, name='index'),
    url(r'^musicians/$', view=views.MusicianListView.as_view(), name='musician_list_view'),
    url(r'^groups/$', view=views.MusicalGropuListView.as_view(), name='musical_group_list_view'),
    url(r'^musicians/(?P<id>\d+)/', view=views.MusicianView.as_view(), name='musician_view'),
    # url(r'^musicians/(?P<pk>\d+)/', view=views.MusicianDetailView.as_view(), name='musicianPage')

]

lab_6/Entertainment/gilp/models.py
from django.db import models

# Create your models here.


class MusicalGroup(models.Model):
    class Meta:
        db_table = 'musicalgroup'
    title = models.CharField(max_length=100, null=False)
    style = models.CharField(max_length=120, null=True)
    country = models.CharField(max_length=40, null=True)

    def __str__(self):
        return self.title


class Musician(models.Model):
    class Meta:
        db_table = 'musician'
    name = models.CharField(max_length=100, null=False)
    birth = models.DateField(null=True)
    role = models.CharField(max_length=70, null=True)
    group = models.ManyToManyField(MusicalGroup, through='Membership')

    def __str__(self):
        return self.name


class Membership(models.Model):
    class Meta:
        db_table = 'membership'
    musicalGroup = models.ForeignKey(MusicalGroup)
    musician = models.ForeignKey(Musician)
    entered = models.DateField(null=True)
    left = models.DateField(null=True)


class Account(models.Model):
    class Meta:
        db_table = 'musicianaccount'
    name = models.CharField(max_length=30, null=True)
    login = models.CharField(max_length=20, null=False)
    email = models.CharField(max_length=30, null=False)
    password = models.CharField(max_length=30, null=False)
    owner = models.OneToOneField(Musician, on_delete=models.CASCADE, null=True)

lab_6/Entertainment/gilp/forms.py
from django import forms
from .models import *


class RegistrationForm(forms.Form):
    class Meta:
        model = Account
        exclude = ['name', 'login', 'password', 'owner']
    username = forms.CharField(min_length=5, label='login')
    password = forms.CharField(min_length=6, widget=forms.PasswordInput, label='password')
    password2 = forms.CharField(min_length=6, widget=forms.PasswordInput, label='password again')


class AuthenticationForm(forms.Form):
    class Meta:
        model = Account
        exclude = ['name', 'email', 'owner']
    login = forms.CharField(min_length=5, label='Login')
    password = forms.CharField(min_length=6, widget=forms.PasswordInput, label='Password')

lab_6/Entertainment/gilp/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView, DetailView
from .models import Musician, MusicalGroup, Membership
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
import MySQLdb
from .forms import *


# Create your views here.


class MusicianListView(ListView):
    model = Musician
    context_object_name = 'musicians'
    template_name = 'musicianListPa ge.html'


class MusicalGropuListView(ListView):
    model = MusicalGroup
    context_object_name = 'groups'
    template_name = 'musicalGroupListPage.html'


class MusicianDetailView(DetailView):
    model = Musician

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class MusicianView(View):
    def get(self, request, id):
        mus = Musician.objects.get(id=int(id))
        data = {
            'musician': {
                    'id': mus.id,
                    'name': mus.name,
                    'birth': mus.birth,
                    'role': mus.role
            }
        }
        return render(request, 'musicianPage.html', data)


def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            #

            return HttpResponseRedirect('/login/')
        else:
            form = RegistrationForm()
    return render(request, 'regForm.html', {'form': form})

lab_6/Entertainment/gilp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block elTitle %}{% endblock %}
    <div>
        {% block body %}changeable{% endblock %}
    </div>
</body>
</html>

lab_6/Entertainment/gilp/templates/gameList.html
{% extends 'base.html' %}

{% block title %}List of games{% endblock %}



{% block body %}
    <div class="container">
        <div class="row"><h1>Game List</h1></div>
        {% for game in games %}
        <div class="row">
            {% include 'gameListElement.html' with elem=game %}
        </div>
        {% endfor %}
    </div>
{% endblock %}

lab_6/Entertainment/templates/gilp/authForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

lab_6/Entertainment/templates/gilp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div>
        {% block content %}{% endblock %}
    </div>
</body>
</html>

lab_6/Entertainment/templates/gilp/listElement.html
<div class="well"><a href="{% url 'gilp:musician_view' elem.id %}">{{ elem.title }}</a></div>

lab_6/Entertainment/templates/gilp/musicalGroupListPage.html
{% extends 'base.html' %}

{% block title %}List of Musical Groups{% endblock %}

{% block content %}
    <div class="container">
        <div class="row"><h1>Groups</h1></div>
        <div class="row">
            <div class="col-xs-2"><b>Id</b></div>
            <div class="col-xs-2"><b>Title</b></div>
            <div class="col-xs-2"><b>Style</b></div>
            <div class="col-xs-2"><b>Country</b></div>
        </div>
        <br>
        {% for group in groups %}
        <div class="row">
            <div class="col-xs-2">{{ group.id }}</div>
            <div class="col-xs-2">{{ group.title }}</div>
            <div class="col-xs-2">{{ group.style }}</div>
            <div class="col-xs-2">{{ group.country }}</div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

lab_6/Entertainment/templates/gilp/musicianListPage.html
{% extends 'base.html' %}

{% block title %}List of Musicians{% endblock %}

{% block content %}
    <div class="container">
        <div class="row"><h1>Musicians</h1></div>
        <div class="row">
            <div class="col-xs-2"><b>Id</b></div>
            <div class="col-xs-2"><b>Name</b></div>
            <div class="col-xs-2"><b>Birth</b></div>
            <div class="col-xs-2"><b>Role</b></div>
        </div>
        <br>
        {% for person in musicians %}
        <div class="row">
            <div class="col-xs-2">{{ person.id }}</div>
            <div class="col-xs-2">{{ person.name }}</div>
            <div class="col-xs-2">{{ person.birth }}</div>
            <div class="col-xs-2">{{ person.role }}</div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

lab_6/Entertainment/templates/gilp/musicianPage.html
{% extends 'base.html' %}

{% block title %} Musician {% endblock %}

{% block content %}
    <div class="container">
        <h2>List Element</h2>
        <div class="container">
            <div class="row well">ID: {{ musician.id }}</div>
            <div class="row well">Name: {{ musician.name }}</div>
            <div class="row well">birth: {{ musician.birth }}</div>
            <div class="row well">role: {{ musician.role }}</div>
        </div>
    </div>

{% endblock %}

lab_6/Entertainment/templates/gilp/regForm.html
{% extends 'base.html' %}

{% block title %} Registration {% endblock %}

{% block content %}

<form method="POST">
    {% csrf_tocken %}
    {{ form.as_p }}
    <button type="submit">Зарегистрировать</button>
</form>

{% endblock %}